# Generated by Django 2.2.7 on 2019-11-20 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(db_index=True, editable=False, verbose_name='last updated at')),
                ('productName', models.CharField(max_length=60)),
                ('sku', models.CharField(max_length=10)),
                ('salePrice', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('purchasePrice', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(db_index=True, editable=False, verbose_name='last updated at')),
                ('supplierName', models.CharField(max_length=60)),
                ('supllierCode', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.Supplier'),
        ),
    ]
